-- =============================================
-- 支付系统数据库表设计
-- 渣打银行支付网关对接
-- =============================================

-- 2.1 支付交易主表
CREATE TABLE PAYMENT_TRANSACTION (
    ID NUMBER(19) PRIMARY KEY,
    TRANSACTION_ID VARCHAR2(100) NOT NULL UNIQUE,      -- 内部交易ID
    IDEMPOTENCY_KEY VARCHAR2(200) NOT NULL UNIQUE,     -- 幂等键：订单号+时间戳，用于去重
    ORDER_REFERENCE VARCHAR2(100) NOT NULL,             -- 客户订单编号（如：CSP001xxxxx）

    -- 客户信息
    USER_ID VARCHAR2(50),
    SUBR_NUM VARCHAR2(50),
    CUSTOMER_NAME VARCHAR2(200),

    -- 支付详情
    AMOUNT NUMBER(10,2) NOT NULL,
    CURRENCY VARCHAR2(3) DEFAULT 'HKD',
    PAYMENT_METHOD VARCHAR2(50),                        -- 支付方式：CARD, ALIPAY等

    -- 网关信息
    GATEWAY_NAME VARCHAR2(50) DEFAULT 'STANDARD_CHARTERED',
    GATEWAY_TRANSACTION_ID VARCHAR2(200),               -- 银行交易ID
    GATEWAY_ORDER_NO VARCHAR2(200),                     -- 银行订单号

    -- 状态管理
    PAYMENT_STATUS VARCHAR2(20) NOT NULL,               -- INIT, PENDING, SUCCESS, FAILED, TIMEOUT, REFUNDED
    PREVIOUS_STATUS VARCHAR2(20),                       -- 用于审计追踪
    STATUS_UPDATE_TIME DATE,

    -- ECR和环境
    ECR_ID VARCHAR2(100),                               -- 收银台ID（如：W30000000718xxxx）
    SID VARCHAR2(50),                                   -- 会话ID（如：cs_acq）
    ENVIRONMENT VARCHAR2(20) DEFAULT 'PROD',            -- PROD, UAT, DEV

    -- 回调信息
    CALLBACK_RECEIVED NUMBER(1) DEFAULT 0,              -- 0=否, 1=是
    CALLBACK_COUNT NUMBER(5) DEFAULT 0,                 -- 收到回调次数
    LAST_CALLBACK_TIME DATE,

    -- 对账
    RECONCILIATION_STATUS VARCHAR2(20),                 -- MATCHED, MISMATCH, PENDING
    RECONCILIATION_TIME DATE,
    LAST_QUERY_TIME DATE,                               -- 最后一次查询银行状态时间

    -- 审计追踪
    VERSION NUMBER(10) DEFAULT 0,                       -- 乐观锁版本号
    CREATE_TIME DATE DEFAULT SYSDATE NOT NULL,
    UPDATE_TIME DATE DEFAULT SYSDATE NOT NULL,
    CREATE_USER VARCHAR2(100),
    UPDATE_USER VARCHAR2(100),

    -- 附加信息
    REMARKS VARCHAR2(2000),
    ERROR_MESSAGE VARCHAR2(2000),

    CONSTRAINT CHK_PAYMENT_STATUS CHECK (PAYMENT_STATUS IN ('INIT', 'PENDING', 'SUCCESS', 'FAILED', 'TIMEOUT', 'REFUNDED', 'RECONCILING'))
);

-- 性能优化索引
CREATE INDEX IDX_PT_ORDER_REF ON PAYMENT_TRANSACTION(ORDER_REFERENCE);
CREATE INDEX IDX_PT_GATEWAY_TXN ON PAYMENT_TRANSACTION(GATEWAY_TRANSACTION_ID);
CREATE INDEX IDX_PT_STATUS ON PAYMENT_TRANSACTION(PAYMENT_STATUS);
CREATE INDEX IDX_PT_CREATE_TIME ON PAYMENT_TRANSACTION(CREATE_TIME);
CREATE INDEX IDX_PT_USER_ID ON PAYMENT_TRANSACTION(USER_ID);

COMMENT ON TABLE PAYMENT_TRANSACTION IS '支付交易主表';
COMMENT ON COLUMN PAYMENT_TRANSACTION.TRANSACTION_ID IS '内部交易ID';
COMMENT ON COLUMN PAYMENT_TRANSACTION.IDEMPOTENCY_KEY IS '幂等键，防止重复支付';
COMMENT ON COLUMN PAYMENT_TRANSACTION.VERSION IS '乐观锁版本号';


-- 2.2 回调日志表
CREATE TABLE PAYMENT_CALLBACK_LOG (
    ID NUMBER(19) PRIMARY KEY,
    TRANSACTION_ID VARCHAR2(100) NOT NULL,
    CALLBACK_TIME DATE DEFAULT SYSDATE NOT NULL,

    -- 请求信息
    CALLBACK_URL VARCHAR2(500),
    REQUEST_METHOD VARCHAR2(10),
    REQUEST_HEADERS CLOB,
    REQUEST_BODY CLOB,
    REQUEST_IP VARCHAR2(50),

    -- 响应信息
    PROCESSING_STATUS VARCHAR2(20),                     -- SUCCESS, FAILED, DUPLICATE
    PROCESSING_TIME_MS NUMBER(10),
    ERROR_MESSAGE VARCHAR2(2000),

    -- 签名验证
    SIGNATURE_VALID NUMBER(1),                          -- 0=否, 1=是
    SIGNATURE_VALUE VARCHAR2(500),

    -- 网关信息
    GATEWAY_STATUS VARCHAR2(50),
    GATEWAY_MESSAGE VARCHAR2(1000),
    GATEWAY_TRANSACTION_ID VARCHAR2(200),

    -- 审计
    CREATE_TIME DATE DEFAULT SYSDATE NOT NULL,

    CONSTRAINT FK_PCL_TRANSACTION FOREIGN KEY (TRANSACTION_ID)
        REFERENCES PAYMENT_TRANSACTION(TRANSACTION_ID)
);

CREATE INDEX IDX_PCL_TXN_ID ON PAYMENT_CALLBACK_LOG(TRANSACTION_ID);
CREATE INDEX IDX_PCL_CALLBACK_TIME ON PAYMENT_CALLBACK_LOG(CALLBACK_TIME);

COMMENT ON TABLE PAYMENT_CALLBACK_LOG IS '回调日志表，记录所有回调尝试';


-- 2.3 对账记录表
CREATE TABLE PAYMENT_RECONCILIATION (
    ID NUMBER(19) PRIMARY KEY,
    RECONCILIATION_DATE DATE NOT NULL,
    RECONCILIATION_TYPE VARCHAR2(50),                   -- DAILY, MANUAL, AUTO_RETRY

    -- 统计信息
    TOTAL_TRANSACTIONS NUMBER(10),
    MATCHED_COUNT NUMBER(10),
    MISMATCH_COUNT NUMBER(10),
    TIMEOUT_COUNT NUMBER(10),
    PENDING_COUNT NUMBER(10),

    -- 状态
    RECONCILIATION_STATUS VARCHAR2(20),                 -- IN_PROGRESS, COMPLETED, FAILED
    START_TIME DATE,
    END_TIME DATE,

    -- 详情
    MISMATCH_TRANSACTION_IDS CLOB,                      -- 不匹配交易ID的JSON数组
    ERROR_MESSAGE VARCHAR2(2000),

    -- 审计
    CREATE_TIME DATE DEFAULT SYSDATE NOT NULL,
    CREATE_USER VARCHAR2(100),

    CONSTRAINT CHK_RECON_STATUS CHECK (RECONCILIATION_STATUS IN ('IN_PROGRESS', 'COMPLETED', 'FAILED'))
);

CREATE INDEX IDX_PR_DATE ON PAYMENT_RECONCILIATION(RECONCILIATION_DATE);

COMMENT ON TABLE PAYMENT_RECONCILIATION IS '对账记录表';


-- 2.4 支付订单映射表
CREATE TABLE PAYMENT_ORDER_MAPPING (
    ID NUMBER(19) PRIMARY KEY,
    TRANSACTION_ID VARCHAR2(100) NOT NULL,
    ORDER_REFERENCE VARCHAR2(100) NOT NULL,

    -- 订单信息
    ORDER_TYPE VARCHAR2(50),                            -- ACQUISITION, RENEWAL, TOP_UP
    ORDER_STATUS VARCHAR2(20),                          -- CREATED, CONFIRMED, FAILED
    ORDER_AMOUNT NUMBER(10,2),

    -- 确认信息
    CONFIRMED NUMBER(1) DEFAULT 0,                      -- 0=否, 1=是
    CONFIRM_TIME DATE,
    CONFIRM_USER VARCHAR2(100),

    -- 审计
    CREATE_TIME DATE DEFAULT SYSDATE NOT NULL,
    UPDATE_TIME DATE DEFAULT SYSDATE NOT NULL,

    CONSTRAINT FK_POM_TRANSACTION FOREIGN KEY (TRANSACTION_ID)
        REFERENCES PAYMENT_TRANSACTION(TRANSACTION_ID),
    CONSTRAINT UK_POM_ORDER UNIQUE (ORDER_REFERENCE, TRANSACTION_ID)
);

CREATE INDEX IDX_POM_TXN_ID ON PAYMENT_ORDER_MAPPING(TRANSACTION_ID);
CREATE INDEX IDX_POM_ORDER_REF ON PAYMENT_ORDER_MAPPING(ORDER_REFERENCE);

COMMENT ON TABLE PAYMENT_ORDER_MAPPING IS '支付订单映射表';


-- 2.5 支付配置表
CREATE TABLE PAYMENT_CONFIG (
    ID NUMBER(19) PRIMARY KEY,
    CONFIG_KEY VARCHAR2(100) NOT NULL UNIQUE,
    CONFIG_VALUE VARCHAR2(2000),
    CONFIG_TYPE VARCHAR2(50),                           -- STRING, NUMBER, JSON, ENCRYPTED
    DESCRIPTION VARCHAR2(500),
    ENVIRONMENT VARCHAR2(20),                           -- PROD, UAT, DEV
    ENABLED NUMBER(1) DEFAULT 1,

    -- 审计
    CREATE_TIME DATE DEFAULT SYSDATE NOT NULL,
    UPDATE_TIME DATE DEFAULT SYSDATE NOT NULL,
    UPDATE_USER VARCHAR2(100)
);

COMMENT ON TABLE PAYMENT_CONFIG IS '支付配置表';


-- 2.6 创建序列
CREATE SEQUENCE SEQ_PAYMENT_TRANSACTION START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_PAYMENT_CALLBACK_LOG START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_PAYMENT_RECONCILIATION START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_PAYMENT_ORDER_MAPPING START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_PAYMENT_CONFIG START WITH 1 INCREMENT BY 1 NOCACHE;


-- 2.7 插入默认配置
INSERT INTO PAYMENT_CONFIG VALUES (SEQ_PAYMENT_CONFIG.NEXTVAL, 'scb.api.endpoint', 'https://api.standardchartered.com/payment', 'STRING', '渣打银行API端点', 'PROD', 1, SYSDATE, SYSDATE, 'SYSTEM');
INSERT INTO PAYMENT_CONFIG VALUES (SEQ_PAYMENT_CONFIG.NEXTVAL, 'scb.timeout.seconds', '120', 'NUMBER', '支付超时阈值（秒）', 'PROD', 1, SYSDATE, SYSDATE, 'SYSTEM');
INSERT INTO PAYMENT_CONFIG VALUES (SEQ_PAYMENT_CONFIG.NEXTVAL, 'scb.callback.retry.max', '5', 'NUMBER', '回调最大重试次数', 'PROD', 1, SYSDATE, SYSDATE, 'SYSTEM');
INSERT INTO PAYMENT_CONFIG VALUES (SEQ_PAYMENT_CONFIG.NEXTVAL, 'reconciliation.cron', '0 */30 * * * ?', 'STRING', '对账任务Cron表达式', 'PROD', 1, SYSDATE, SYSDATE, 'SYSTEM');
COMMIT;

-- 验证
SELECT 'Tables created successfully!' as STATUS FROM DUAL;

