-- =============================================
-- 电讯行业优惠券系统 - Oracle DDL脚本
-- =============================================

-- 优惠券模板表
CREATE TABLE T_COUPON_TEMPLATE (
    ID NUMBER(19) PRIMARY KEY,
    NAME VARCHAR2(100) NOT NULL,
    DESCRIPTION VARCHAR2(500),
    COUPON_TYPE NUMBER(2) NOT NULL,
    GRANT_TYPE NUMBER(2) NOT NULL,
    FACE_VALUE NUMBER(10,2),
    DISCOUNT_RATE NUMBER(3,2),
    THRESHOLD_AMOUNT NUMBER(10,2) DEFAULT 0,
    APPLICABLE_PACKAGES VARCHAR2(500),
    APPLICABLE_SERVICES VARCHAR2(500),
    STACKABLE NUMBER(1) DEFAULT 0,
    VALIDITY_TYPE NUMBER(1) NOT NULL,
    VALID_START_TIME TIMESTAMP,
    VALID_END_TIME TIMESTAMP,
    VALID_DAYS NUMBER(5),
    TOTAL_QUANTITY NUMBER(10) NOT NULL,
    ISSUED_QUANTITY NUMBER(10) DEFAULT 0,
    LIMIT_PER_USER NUMBER(5) DEFAULT 1,
    STATUS NUMBER(1) DEFAULT 0,
    CREATE_TIME TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATE_TIME TIMESTAMP DEFAULT SYSTIMESTAMP,
    CREATE_BY VARCHAR2(50),
    DELETED NUMBER(1) DEFAULT 0
);

COMMENT ON TABLE T_COUPON_TEMPLATE IS '优惠券模板表';
COMMENT ON COLUMN T_COUPON_TEMPLATE.COUPON_TYPE IS '券类型:1现金券,2折扣券,3满减券,4免单券,5流量券,6通话券';
COMMENT ON COLUMN T_COUPON_TEMPLATE.GRANT_TYPE IS '发放类型:1套餐月度,2活动营销,3消费激励,4推荐奖励,5挽留客户,6秒杀抢购,7手动发放';
COMMENT ON COLUMN T_COUPON_TEMPLATE.VALIDITY_TYPE IS '有效期类型:1绝对时间,2相对时间';

CREATE INDEX IDX_TEMPLATE_STATUS ON T_COUPON_TEMPLATE(STATUS);
CREATE INDEX IDX_TEMPLATE_GRANT_TYPE ON T_COUPON_TEMPLATE(GRANT_TYPE);

-- 优惠券实例表
CREATE TABLE T_COUPON (
    ID NUMBER(19) PRIMARY KEY,
    COUPON_CODE VARCHAR2(32) NOT NULL,
    TEMPLATE_ID NUMBER(19) NOT NULL,
    BATCH_ID NUMBER(19),
    USER_ID VARCHAR2(50),
    USER_MOBILE VARCHAR2(20),
    COUPON_TYPE NUMBER(2) NOT NULL,
    FACE_VALUE NUMBER(10,2),
    DISCOUNT_RATE NUMBER(3,2),
    THRESHOLD_AMOUNT NUMBER(10,2),
    STATUS NUMBER(1) DEFAULT 1,
    VALID_START_TIME TIMESTAMP NOT NULL,
    VALID_END_TIME TIMESTAMP NOT NULL,
    CLAIM_TIME TIMESTAMP,
    USE_TIME TIMESTAMP,
    ORDER_NO VARCHAR2(50),
    GRANT_TYPE NUMBER(2),
    GRANT_SOURCE VARCHAR2(50),
    CREATE_TIME TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATE_TIME TIMESTAMP DEFAULT SYSTIMESTAMP,
    DELETED NUMBER(1) DEFAULT 0,
    CONSTRAINT UK_COUPON_CODE UNIQUE (COUPON_CODE)
);

COMMENT ON TABLE T_COUPON IS '优惠券实例表';
COMMENT ON COLUMN T_COUPON.STATUS IS '状态:1可用,2已使用,3已过期,4已锁定,5已取消';

CREATE INDEX IDX_COUPON_USER_ID ON T_COUPON(USER_ID);
CREATE INDEX IDX_COUPON_STATUS ON T_COUPON(STATUS);
CREATE INDEX IDX_COUPON_TEMPLATE_ID ON T_COUPON(TEMPLATE_ID);
CREATE INDEX IDX_COUPON_VALID_END ON T_COUPON(VALID_END_TIME);
-- 防止重复领取的唯一索引
CREATE UNIQUE INDEX UK_USER_TEMPLATE ON T_COUPON(USER_ID, TEMPLATE_ID, GRANT_SOURCE) WHERE DELETED = 0;

-- 秒杀活动表
CREATE TABLE T_SECKILL_ACTIVITY (
    ID NUMBER(19) PRIMARY KEY,
    NAME VARCHAR2(100) NOT NULL,
    DESCRIPTION VARCHAR2(500),
    TEMPLATE_ID NUMBER(19) NOT NULL,
    START_TIME TIMESTAMP NOT NULL,
    END_TIME TIMESTAMP NOT NULL,
    TOTAL_STOCK NUMBER(10) NOT NULL,
    REMAIN_STOCK NUMBER(10) NOT NULL,
    LIMIT_PER_USER NUMBER(5) DEFAULT 1,
    POINTS_CHANNEL NUMBER(2),
    REQUIRED_POINTS NUMBER(10),
    REQUIRED_AMOUNT NUMBER(10,2),
    VIP_ONLY NUMBER(1) DEFAULT 0,
    VIP_LEVEL_REQUIRED NUMBER(2),
    STATUS NUMBER(1) DEFAULT 0,
    CREATE_TIME TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATE_TIME TIMESTAMP DEFAULT SYSTIMESTAMP,
    CREATE_BY VARCHAR2(50),
    DELETED NUMBER(1) DEFAULT 0
);

COMMENT ON TABLE T_SECKILL_ACTIVITY IS '秒杀活动表';
COMMENT ON COLUMN T_SECKILL_ACTIVITY.POINTS_CHANNEL IS '积分渠道:1内部积分,2信用卡积分,3第三方积分';
COMMENT ON COLUMN T_SECKILL_ACTIVITY.STATUS IS '状态:0未开始,1进行中,2已暂停,3已结束,4已售罄';

CREATE INDEX IDX_SECKILL_STATUS ON T_SECKILL_ACTIVITY(STATUS);
CREATE INDEX IDX_SECKILL_START_TIME ON T_SECKILL_ACTIVITY(START_TIME);

-- 秒杀订单表
CREATE TABLE T_SECKILL_ORDER (
    ID NUMBER(19) PRIMARY KEY,
    ORDER_NO VARCHAR2(50) NOT NULL,
    ACTIVITY_ID NUMBER(19) NOT NULL,
    USER_ID VARCHAR2(50) NOT NULL,
    USER_MOBILE VARCHAR2(20),
    COUPON_ID NUMBER(19),
    POINTS_CHANNEL NUMBER(2),
    POINTS_USED NUMBER(10),
    AMOUNT_PAID NUMBER(10,2),
    STATUS NUMBER(1) DEFAULT 0,
    FAIL_REASON VARCHAR2(200),
    GRAB_TIME TIMESTAMP NOT NULL,
    CREATE_TIME TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATE_TIME TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT UK_SECKILL_ORDER_NO UNIQUE (ORDER_NO)
);

COMMENT ON TABLE T_SECKILL_ORDER IS '秒杀订单表';
COMMENT ON COLUMN T_SECKILL_ORDER.STATUS IS '状态:0待处理,1成功,2失败,3已退款';

CREATE INDEX IDX_SECKILL_ORDER_USER ON T_SECKILL_ORDER(USER_ID);
CREATE INDEX IDX_SECKILL_ORDER_ACTIVITY ON T_SECKILL_ORDER(ACTIVITY_ID);
-- 防止重复抢购
CREATE UNIQUE INDEX UK_USER_ACTIVITY ON T_SECKILL_ORDER(USER_ID, ACTIVITY_ID) WHERE STATUS IN (0, 1);

-- 优惠券使用记录表
CREATE TABLE T_COUPON_USE_RECORD (
    ID NUMBER(19) PRIMARY KEY,
    COUPON_ID NUMBER(19) NOT NULL,
    COUPON_CODE VARCHAR2(32) NOT NULL,
    USER_ID VARCHAR2(50) NOT NULL,
    ORDER_NO VARCHAR2(50) NOT NULL,
    ORIGINAL_AMOUNT NUMBER(10,2),
    DISCOUNT_AMOUNT NUMBER(10,2),
    ACTUAL_AMOUNT NUMBER(10,2),
    USE_SCENE VARCHAR2(50),
    USE_TIME TIMESTAMP NOT NULL,
    CREATE_TIME TIMESTAMP DEFAULT SYSTIMESTAMP
);

COMMENT ON TABLE T_COUPON_USE_RECORD IS '优惠券使用记录表';

CREATE INDEX IDX_USE_RECORD_COUPON ON T_COUPON_USE_RECORD(COUPON_ID);
CREATE INDEX IDX_USE_RECORD_USER ON T_COUPON_USE_RECORD(USER_ID);
CREATE INDEX IDX_USE_RECORD_ORDER ON T_COUPON_USE_RECORD(ORDER_NO);

-- 发放规则表(消费激励/套餐赠送规则)
CREATE TABLE T_COUPON_RULE (
    ID NUMBER(19) PRIMARY KEY,
    NAME VARCHAR2(100) NOT NULL,
    RULE_TYPE NUMBER(2) NOT NULL,
    TEMPLATE_ID NUMBER(19) NOT NULL,
    TRIGGER_CONDITION VARCHAR2(500),
    THRESHOLD_AMOUNT NUMBER(10,2),
    PACKAGE_CODES VARCHAR2(500),
    CRON_EXPRESSION VARCHAR2(50),
    STATUS NUMBER(1) DEFAULT 1,
    CREATE_TIME TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATE_TIME TIMESTAMP DEFAULT SYSTIMESTAMP,
    DELETED NUMBER(1) DEFAULT 0
);

COMMENT ON TABLE T_COUPON_RULE IS '优惠券发放规则表';
COMMENT ON COLUMN T_COUPON_RULE.RULE_TYPE IS '规则类型:1消费达标,2套餐绑定,3定时发放';

CREATE INDEX IDX_RULE_STATUS ON T_COUPON_RULE(STATUS);
CREATE INDEX IDX_RULE_TEMPLATE ON T_COUPON_RULE(TEMPLATE_ID);

-- 序列(用于生成券码)
CREATE SEQUENCE SEQ_COUPON_CODE START WITH 1 INCREMENT BY 1 NOCACHE;

