-- =============================================
-- 电讯行业优惠券系统 - Oracle DDL脚本
-- =============================================

-- 优惠券模板表
CREATE TABLE T_COUPON_TEMPLATE (
    ID NUMBER(19) PRIMARY KEY,
    NAME VARCHAR2(100) NOT NULL,
    DESCRIPTION VARCHAR2(500),
    COUPON_TYPE NUMBER(2) NOT NULL,
    GRANT_TYPE NUMBER(2) NOT NULL,
    FACE_VALUE NUMBER(10,2),
    DISCOUNT_RATE NUMBER(3,2),
    THRESHOLD_AMOUNT NUMBER(10,2) DEFAULT 0,
    APPLICABLE_PACKAGES VARCHAR2(500),
    APPLICABLE_SERVICES VARCHAR2(500),
    STACKABLE NUMBER(1) DEFAULT 0,
    VALIDITY_TYPE NUMBER(1) NOT NULL,
    VALID_START_TIME TIMESTAMP,
    VALID_END_TIME TIMESTAMP,
    VALID_DAYS NUMBER(5),
    TOTAL_QUANTITY NUMBER(10) NOT NULL,
    ISSUED_QUANTITY NUMBER(10) DEFAULT 0,
    LIMIT_PER_USER NUMBER(5) DEFAULT 1,
    STATUS NUMBER(1) DEFAULT 0,
    CREATE_TIME TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATE_TIME TIMESTAMP DEFAULT SYSTIMESTAMP,
    CREATE_BY VARCHAR2(50),
    DELETED NUMBER(1) DEFAULT 0
);

COMMENT ON TABLE T_COUPON_TEMPLATE IS '优惠券模板表';
COMMENT ON COLUMN T_COUPON_TEMPLATE.COUPON_TYPE IS '券类型:1现金券,2折扣券,3满减券,4免单券,5流量券,6通话券';
COMMENT ON COLUMN T_COUPON_TEMPLATE.GRANT_TYPE IS '发放类型:1套餐月度,2活动营销,3消费激励,4推荐奖励,5挽留客户,6秒杀抢购,7手动发放';
COMMENT ON COLUMN T_COUPON_TEMPLATE.VALIDITY_TYPE IS '有效期类型:1绝对时间,2相对时间';

CREATE INDEX IDX_TEMPLATE_STATUS ON T_COUPON_TEMPLATE(STATUS);
CREATE INDEX IDX_TEMPLATE_GRANT_TYPE ON T_COUPON_TEMPLATE(GRANT_TYPE);

-- 优惠券实例表
CREATE TABLE T_COUPON (
    ID NUMBER(19) PRIMARY KEY,
    COUPON_CODE VARCHAR2(32) NOT NULL,
    TEMPLATE_ID NUMBER(19) NOT NULL,
    BATCH_ID NUMBER(19),
    USER_ID VARCHAR2(50),
    USER_MOBILE VARCHAR2(20),
    COUPON_TYPE NUMBER(2) NOT NULL,
    FACE_VALUE NUMBER(10,2),
    DISCOUNT_RATE NUMBER(3,2),
    THRESHOLD_AMOUNT NUMBER(10,2),
    STATUS NUMBER(1) DEFAULT 1,
    VALID_START_TIME TIMESTAMP NOT NULL,
    VALID_END_TIME TIMESTAMP NOT NULL,
    CLAIM_TIME TIMESTAMP,
    USE_TIME TIMESTAMP,
    ORDER_NO VARCHAR2(50),
    GRANT_TYPE NUMBER(2),
    GRANT_SOURCE VARCHAR2(50),
    CREATE_TIME TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATE_TIME TIMESTAMP DEFAULT SYSTIMESTAMP,
    DELETED NUMBER(1) DEFAULT 0,
    CONSTRAINT UK_COUPON_CODE UNIQUE (COUPON_CODE)
);

COMMENT ON TABLE T_COUPON IS '优惠券实例表';
COMMENT ON COLUMN T_COUPON.STATUS IS '状态:1可用,2已使用,3已过期,4已锁定,5已取消';

CREATE INDEX IDX_COUPON_USER_ID ON T_COUPON(USER_ID);
CREATE INDEX IDX_COUPON_STATUS ON T_COUPON(STATUS);
CREATE INDEX IDX_COUPON_TEMPLATE_ID ON T_COUPON(TEMPLATE_ID);
CREATE INDEX IDX_COUPON_VALID_END ON T_COUPON(VALID_END_TIME);
-- 防止重复领取的唯一索引
CREATE UNIQUE INDEX UK_USER_TEMPLATE ON T_COUPON(USER_ID, TEMPLATE_ID, GRANT_SOURCE) WHERE DELETED = 0;

-- 秒杀活动表
CREATE TABLE T_SECKILL_ACTIVITY (
    ID NUMBER(19) PRIMARY KEY,
    NAME VARCHAR2(100) NOT NULL,
    DESCRIPTION VARCHAR2(500),
    TEMPLATE_ID NUMBER(19) NOT NULL,
    START_TIME TIMESTAMP NOT NULL,
    END_TIME TIMESTAMP NOT NULL,
    TOTAL_STOCK NUMBER(10) NOT NULL,
    REMAIN_STOCK NUMBER(10) NOT NULL,
    LIMIT_PER_USER NUMBER(5) DEFAULT 1,
    POINTS_CHANNEL NUMBER(2),
    REQUIRED_POINTS NUMBER(10),
    REQUIRED_AMOUNT NUMBER(10,2),
    VIP_ONLY NUMBER(1) DEFAULT 0,
    VIP_LEVEL_REQUIRED NUMBER(2),
    STATUS NUMBER(1) DEFAULT 0,
    CREATE_TIME TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATE_TIME TIMESTAMP DEFAULT SYSTIMESTAMP,
    CREATE_BY VARCHAR2(50),
    DELETED NUMBER(1) DEFAULT 0
);

COMMENT ON TABLE T_SECKILL_ACTIVITY IS '秒杀活动表';
COMMENT ON COLUMN T_SECKILL_ACTIVITY.POINTS_CHANNEL IS '积分渠道:1内部积分,2信用卡积分,3第三方积分';
COMMENT ON COLUMN T_SECKILL_ACTIVITY.STATUS IS '状态:0未开始,1进行中,2已暂停,3已结束,4已售罄';

CREATE INDEX IDX_SECKILL_STATUS ON T_SECKILL_ACTIVITY(STATUS);
CREATE INDEX IDX_SECKILL_START_TIME ON T_SECKILL_ACTIVITY(START_TIME);

-- 秒杀订单表
CREATE TABLE T_SECKILL_ORDER (
    ID NUMBER(19) PRIMARY KEY,
    ORDER_NO VARCHAR2(50) NOT NULL,
    ACTIVITY_ID NUMBER(19) NOT NULL,
    USER_ID VARCHAR2(50) NOT NULL,
    USER_MOBILE VARCHAR2(20),
    COUPON_ID NUMBER(19),
    POINTS_CHANNEL NUMBER(2),
    POINTS_USED NUMBER(10),
    AMOUNT_PAID NUMBER(10,2),
    STATUS NUMBER(1) DEFAULT 0,
    FAIL_REASON VARCHAR2(200),
    GRAB_TIME TIMESTAMP NOT NULL,
    CREATE_TIME TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATE_TIME TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT UK_SECKILL_ORDER_NO UNIQUE (ORDER_NO)
);

COMMENT ON TABLE T_SECKILL_ORDER IS '秒杀订单表';
COMMENT ON COLUMN T_SECKILL_ORDER.STATUS IS '状态:0待处理,1成功,2失败,3已退款';

CREATE INDEX IDX_SECKILL_ORDER_USER ON T_SECKILL_ORDER(USER_ID);
CREATE INDEX IDX_SECKILL_ORDER_ACTIVITY ON T_SECKILL_ORDER(ACTIVITY_ID);
-- 防止重复抢购
CREATE UNIQUE INDEX UK_USER_ACTIVITY ON T_SECKILL_ORDER(USER_ID, ACTIVITY_ID) WHERE STATUS IN (0, 1);

-- 优惠券使用记录表
CREATE TABLE T_COUPON_USE_RECORD (
    ID NUMBER(19) PRIMARY KEY,
    COUPON_ID NUMBER(19) NOT NULL,
    COUPON_CODE VARCHAR2(32) NOT NULL,
    USER_ID VARCHAR2(50) NOT NULL,
    ORDER_NO VARCHAR2(50) NOT NULL,
    ORIGINAL_AMOUNT NUMBER(10,2),
    DISCOUNT_AMOUNT NUMBER(10,2),
    ACTUAL_AMOUNT NUMBER(10,2),
    USE_SCENE VARCHAR2(50),
    USE_TIME TIMESTAMP NOT NULL,
    CREATE_TIME TIMESTAMP DEFAULT SYSTIMESTAMP
);

COMMENT ON TABLE T_COUPON_USE_RECORD IS '优惠券使用记录表';

CREATE INDEX IDX_USE_RECORD_COUPON ON T_COUPON_USE_RECORD(COUPON_ID);
CREATE INDEX IDX_USE_RECORD_USER ON T_COUPON_USE_RECORD(USER_ID);
CREATE INDEX IDX_USE_RECORD_ORDER ON T_COUPON_USE_RECORD(ORDER_NO);

-- 发放规则表(消费激励/套餐赠送规则)
CREATE TABLE T_COUPON_RULE (
    ID NUMBER(19) PRIMARY KEY,
    NAME VARCHAR2(100) NOT NULL,
    RULE_TYPE NUMBER(2) NOT NULL,
    TEMPLATE_ID NUMBER(19) NOT NULL,
    TRIGGER_CONDITION VARCHAR2(500),
    THRESHOLD_AMOUNT NUMBER(10,2),
    PACKAGE_CODES VARCHAR2(500),
    CRON_EXPRESSION VARCHAR2(50),
    STATUS NUMBER(1) DEFAULT 1,
    CREATE_TIME TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATE_TIME TIMESTAMP DEFAULT SYSTIMESTAMP,
    DELETED NUMBER(1) DEFAULT 0
);

COMMENT ON TABLE T_COUPON_RULE IS '优惠券发放规则表';
COMMENT ON COLUMN T_COUPON_RULE.RULE_TYPE IS '规则类型:1消费达标,2套餐绑定,3定时发放';

CREATE INDEX IDX_RULE_STATUS ON T_COUPON_RULE(STATUS);
CREATE INDEX IDX_RULE_TEMPLATE ON T_COUPON_RULE(TEMPLATE_ID);

-- 序列(用于生成券码)
CREATE SEQUENCE SEQ_COUPON_CODE START WITH 1 INCREMENT BY 1 NOCACHE;


-- =============================================
-- 兑换码批次表（2026-04-17新增）
-- 每次运营生成一批兑换码对应一条批次记录
-- =============================================
CREATE TABLE T_REDEEM_CODE_BATCH (
    ID              NUMBER(19)      PRIMARY KEY,
    BATCH_NAME      VARCHAR2(100)   NOT NULL,
    TEMPLATE_ID     NUMBER(19)      NOT NULL,
    TOTAL_COUNT     NUMBER(10)      NOT NULL,
    REDEEMED_COUNT  NUMBER(10)      DEFAULT 0,
    STATUS          NUMBER(1)       DEFAULT 1,   -- 0生成中 1已激活 2已停用 3已过期
    -- 每个用户在此批次最多可兑换N张码（默认1张，防羊毛党同批次兑多张）
    MAX_PER_USER    NUMBER(5)       DEFAULT 1,
    EXPIRE_TIME     TIMESTAMP       NOT NULL,
    CREATE_BY       VARCHAR2(50),
    REMARK          VARCHAR2(500),
    CREATE_TIME     TIMESTAMP       DEFAULT SYSTIMESTAMP,
    UPDATE_TIME     TIMESTAMP       DEFAULT SYSTIMESTAMP,
    DELETED         NUMBER(1)       DEFAULT 0
);

COMMENT ON TABLE  T_REDEEM_CODE_BATCH              IS '兑换码批次表';
COMMENT ON COLUMN T_REDEEM_CODE_BATCH.STATUS       IS '批次状态:0生成中,1已激活,2已停用,3已过期';

CREATE INDEX IDX_RDBATCH_TEMPLATE ON T_REDEEM_CODE_BATCH(TEMPLATE_ID);
CREATE INDEX IDX_RDBATCH_STATUS   ON T_REDEEM_CODE_BATCH(STATUS);


-- =============================================
-- 兑换码实例表（2026-04-17新增）
-- 每一条记录对应一个可被用户兑换的码
-- =============================================
CREATE TABLE T_COUPON_REDEEM_CODE (
    ID              NUMBER(19)      PRIMARY KEY,
    -- 码格式: CP-{BASE36(ID)}-{HMAC4}，示例: CP-2K5XM1-A3F7
    -- HMAC签名防枚举：无私钥无法伪造有效码
    CODE            VARCHAR2(32)    NOT NULL,
    BATCH_ID        NUMBER(19)      NOT NULL,
    TEMPLATE_ID     NUMBER(19)      NOT NULL,
    STATUS          NUMBER(1)       DEFAULT 0,   -- 0未使用 1已使用 2已过期 3已锁定
    USER_ID         VARCHAR2(50),                -- 兑换成功的用户
    REDEEM_TIME     TIMESTAMP,
    REDEEM_IP       VARCHAR2(50),
    REDEEM_CHANNEL  VARCHAR2(20),                -- APP/WEB/H5/SMS
    -- 失败次数超过MAX_FAIL_COUNT(5次)自动锁定该码，防暴力重试
    FAIL_COUNT      NUMBER(5)       DEFAULT 0,
    -- 已解锁次数；>=2次时强制人工审核，防止攻击者"社工客服反复解锁→暴力枚举"
    UNLOCK_COUNT    NUMBER(3)       DEFAULT 0,
    EXPIRE_TIME     TIMESTAMP       NOT NULL,
    CREATE_TIME     TIMESTAMP       DEFAULT SYSTIMESTAMP,
    UPDATE_TIME     TIMESTAMP       DEFAULT SYSTIMESTAMP,
    DELETED         NUMBER(1)       DEFAULT 0,
    -- 唯一索引：同一码不能重复插入
    CONSTRAINT UK_REDEEM_CODE UNIQUE (CODE)
);

COMMENT ON TABLE  T_COUPON_REDEEM_CODE             IS '兑换码实例表';
COMMENT ON COLUMN T_COUPON_REDEEM_CODE.STATUS      IS '状态:0未使用,1已使用,2已过期,3已锁定(失败超限)';
COMMENT ON COLUMN T_COUPON_REDEEM_CODE.FAIL_COUNT  IS '兑换失败次数，超过5次自动锁定';
COMMENT ON COLUMN T_COUPON_REDEEM_CODE.UNLOCK_COUNT IS '解锁次数，>=2次强制人工审核，防社工攻击';
COMMENT ON COLUMN T_COUPON_REDEEM_CODE.CODE        IS 'HMAC签名码，格式CP-BASE36ID-HMAC4，防枚举';

-- 查询索引
CREATE INDEX IDX_RDCODE_BATCH    ON T_COUPON_REDEEM_CODE(BATCH_ID);
CREATE INDEX IDX_RDCODE_TEMPLATE ON T_COUPON_REDEEM_CODE(TEMPLATE_ID);
CREATE INDEX IDX_RDCODE_STATUS   ON T_COUPON_REDEEM_CODE(STATUS);
CREATE INDEX IDX_RDCODE_USER     ON T_COUPON_REDEEM_CODE(USER_ID);
CREATE INDEX IDX_RDCODE_EXPIRE   ON T_COUPON_REDEEM_CODE(EXPIRE_TIME);


-- =============================================
-- 2026-04-20 新增：兑换码发券补偿任务表（本地消息表）
-- 解决分布式事务问题：CAS成功后发券失败的自动补偿
-- 原理：CAS成功 + 写task 在同一事务，task由Job重试发券
-- =============================================
CREATE TABLE T_GRANT_TASK (
    ID              NUMBER(19)      PRIMARY KEY,
    -- 关联的兑换码
    REDEEM_CODE     VARCHAR2(32)    NOT NULL,
    -- 要发给哪个用户
    USER_ID         VARCHAR2(50)    NOT NULL,
    -- 要发哪个券模板
    TEMPLATE_ID     NUMBER(19)      NOT NULL,
    -- 任务状态: 0=待处理 1=成功 2=失败超限 3=人工取消
    STATUS          NUMBER(1)       DEFAULT 0,
    -- 已重试次数
    RETRY_COUNT     NUMBER(3)       DEFAULT 0,
    -- 最大重试次数（超过后标记失败，人工介入）
    MAX_RETRY       NUMBER(3)       DEFAULT 3,
    -- 发券成功后的券实例ID（用于幂等判断）
    COUPON_ID       NUMBER(19),
    -- 失败原因（用于人工排查）
    FAIL_REASON     VARCHAR2(500),
    -- 下次重试时间（指数退避：1min → 5min → 30min）
    NEXT_RETRY_TIME TIMESTAMP,
    CREATE_TIME     TIMESTAMP       DEFAULT SYSTIMESTAMP,
    UPDATE_TIME     TIMESTAMP       DEFAULT SYSTIMESTAMP
);

COMMENT ON TABLE  T_GRANT_TASK             IS '兑换码发券补偿任务表（本地消息表，解决分布式事务）';
COMMENT ON COLUMN T_GRANT_TASK.STATUS      IS '任务状态:0待处理,1成功,2失败超限需人工,3人工取消';
COMMENT ON COLUMN T_GRANT_TASK.RETRY_COUNT IS '已重试次数，超过MAX_RETRY标记失败';

CREATE INDEX IDX_GRANT_TASK_STATUS ON T_GRANT_TASK(STATUS, NEXT_RETRY_TIME);
CREATE INDEX IDX_GRANT_TASK_CODE   ON T_GRANT_TASK(REDEEM_CODE);


-- =============================================
-- 2026-04-20 新增：Alter语句（已有表新增字段）
-- 如果在已有环境执行，运行以下ALTER
-- =============================================
-- ALTER TABLE T_COUPON_REDEEM_CODE ADD UNLOCK_COUNT NUMBER(3) DEFAULT 0;
-- ALTER TABLE T_REDEEM_CODE_BATCH   ADD MAX_PER_USER NUMBER(5) DEFAULT 1;
-- COMMENT ON COLUMN T_COUPON_REDEEM_CODE.UNLOCK_COUNT IS '解锁次数，>=2次强制人工审核';
-- COMMENT ON COLUMN T_REDEEM_CODE_BATCH.MAX_PER_USER  IS '同一批次同一用户最多可兑换张数';


-- =============================================
-- 2026-04-22 新增：秒杀订单消费重试任务表
-- 解决 Kafka 消费失败直接标记订单失败的问题
-- 临时故障（DB抖动、积分服务超时）时保护用户权益
--
-- 工作流程：
--   Kafka消费失败(临时异常) → 写此表(status=0)
--   → CouponScheduledJob.retrySeckillOrders() 每30s扫描
--   → 指数退避重试：1min → 5min → 30min
--   → 3次仍失败 → status=2 + 发死信Topic + SeckillOrderDltConsumer告警
-- =============================================
CREATE TABLE T_SECKILL_RETRY_TASK (
    ID              NUMBER(19)      PRIMARY KEY,
    ORDER_ID        NUMBER(19)      NOT NULL,       -- 关联 T_SECKILL_ORDER.ID
    ACTIVITY_ID     NUMBER(19)      NOT NULL,       -- 关联活动ID（日志用）
    USER_ID         VARCHAR2(50)    NOT NULL,       -- 用户ID（告警用）
    -- 0=待重试  1=重试成功  2=失败超限（需人工处理）
    STATUS          NUMBER(1)       DEFAULT 0,
    RETRY_COUNT     NUMBER(3)       DEFAULT 0,      -- 已重试次数
    MAX_RETRY       NUMBER(3)       DEFAULT 3,      -- 最大重试次数
    FAIL_REASON     VARCHAR2(500),                  -- 最后一次失败原因
    -- 下次重试时间（指数退避：第1次1min, 第2次5min, 第3次30min）
    NEXT_RETRY_TIME TIMESTAMP,
    CREATE_TIME     TIMESTAMP       DEFAULT SYSTIMESTAMP,
    UPDATE_TIME     TIMESTAMP       DEFAULT SYSTIMESTAMP
);

COMMENT ON TABLE  T_SECKILL_RETRY_TASK              IS '秒杀订单消费重试任务表（保护用户权益，替代直接失败）';
COMMENT ON COLUMN T_SECKILL_RETRY_TASK.STATUS       IS '任务状态:0待重试,1重试成功,2失败超限需人工';
COMMENT ON COLUMN T_SECKILL_RETRY_TASK.RETRY_COUNT  IS '已重试次数，达到MAX_RETRY后STATUS→2进死信';
COMMENT ON COLUMN T_SECKILL_RETRY_TASK.NEXT_RETRY_TIME IS '下次重试时间，指数退避：1/5/30分钟';

-- 查询索引：Job扫描待重试任务用
CREATE INDEX IDX_SECKILL_RETRY_PENDING ON T_SECKILL_RETRY_TASK(STATUS, NEXT_RETRY_TIME);
-- 关联查询索引
CREATE INDEX IDX_SECKILL_RETRY_ORDER   ON T_SECKILL_RETRY_TASK(ORDER_ID);
