DROP TABLE FES.ZZ_POS_ITEM_NB CASCADE CONSTRAINTS;

CREATE TABLE FES.ZZ_POS_ITEM_NB
(
  SUBSCRIBER      VARCHAR2(20 BYTE),
  CELLULAR        VARCHAR2(20 BYTE),
  DEALER          VARCHAR2(10 BYTE),
  SYSTEM_IND      VARCHAR2(1 BYTE),
  BIN_NUMBER      VARCHAR2(10 BYTE),
  INVOICE_NO      VARCHAR2(10 BYTE),
  INV_DATE        DATE,
  INV_TYPE        VARCHAR2(3 BYTE),
  INV_AMOUNT      NUMBER(12,2),
  OS_AMOUNT       NUMBER(12,2),
  SETTLED_AMT     NUMBER(12,2),
  NON_SUB_FEE     NUMBER(12,2),
  SUB_FEE         NUMBER(12,2),
  ACTIVE          VARCHAR2(1 BYTE),
  CHINA_ROAM      VARCHAR2(1 BYTE),
  BARRED          VARCHAR2(1 BYTE),
  UNBILL_AMT      NUMBER(12,2),
  CHARGE_TYPE     VARCHAR2(10 BYTE),
  STAT            VARCHAR2(1 BYTE),
  DATE_SUSPENSED  DATE,
  ACCOUNT_NO      VARCHAR2(20 BYTE),
  REFERENCE1      VARCHAR2(30 BYTE)
)
TABLESPACE FESEXTD01
PCTUSED    0
PCTFREE    0
INITRANS   10
MAXTRANS   255
STORAGE    (
            INITIAL          180M
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOLOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX FES.ZZ_POS_ITEM_NB_ID1 ON FES.ZZ_POS_ITEM_NB
(SUBSCRIBER, INV_DATE, INVOICE_NO)
LOGGING
TABLESPACE FESEXTI01
PCTFREE    10
INITRANS   10
MAXTRANS   255
STORAGE    (
            INITIAL          70M
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX FES.ZZ_POS_ITEM_NB_ID2 ON FES.ZZ_POS_ITEM_NB
(INV_DATE, INVOICE_NO)
LOGGING
TABLESPACE FESEXTI01
PCTFREE    10
INITRANS   10
MAXTRANS   255
STORAGE    (
            INITIAL          70M
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX FES.ZZ_POS_ITEM_NB_ID3 ON FES.ZZ_POS_ITEM_NB
(CELLULAR, INV_DATE, INVOICE_NO)
LOGGING
TABLESPACE FESEXTI01
PCTFREE    10
INITRANS   10
MAXTRANS   255
STORAGE    (
            INITIAL          70M
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX FES.ZZ_POS_ITEM_NB_ID4 ON FES.ZZ_POS_ITEM_NB
(INVOICE_NO)
LOGGING
TABLESPACE FESEXTI01
PCTFREE    10
INITRANS   10
MAXTRANS   255
STORAGE    (
            INITIAL          70M
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX FES.ZZ_POS_ITEM_NB_ID5 ON FES.ZZ_POS_ITEM_NB
(SUBSCRIBER, INVOICE_NO)
LOGGING
TABLESPACE FESEXTI01
PCTFREE    10
INITRANS   10
MAXTRANS   255
STORAGE    (
            INITIAL          70M
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX FES.ZZ_POS_ITEM_NB_ID6 ON FES.ZZ_POS_ITEM_NB
(SYSTEM_IND, "OS_AMOUNT" DESC)
LOGGING
TABLESPACE FESEXTI01
PCTFREE    10
INITRANS   10
MAXTRANS   255
STORAGE    (
            INITIAL          70M
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX FES.ZZ_POS_ITEM_NB_ID7 ON FES.ZZ_POS_ITEM_NB
(INV_TYPE, SUBSCRIBER)
LOGGING
TABLESPACE FESEXTI01
PCTFREE    10
INITRANS   10
MAXTRANS   255
STORAGE    (
            INITIAL          70M
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX FES.ZZ_POS_ITEM_NB_ID8 ON FES.ZZ_POS_ITEM_NB
(SUBSCRIBER, SYSTEM_IND)
LOGGING
TABLESPACE FESEXTI01
PCTFREE    10
INITRANS   10
MAXTRANS   255
STORAGE    (
            INITIAL          70M
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX FES.ZZ_POS_ITEM_NB_ID9 ON FES.ZZ_POS_ITEM_NB
(SUBSCRIBER, CELLULAR)
LOGGING
TABLESPACE FESEXTI01
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;



DROP PUBLIC SYNONYM ZZ_POS_ITEM_NB;

CREATE PUBLIC SYNONYM ZZ_POS_ITEM_NB FOR FES.ZZ_POS_ITEM_NB;


GRANT DELETE, INSERT, SELECT, UPDATE ON FES.ZZ_POS_ITEM_NB TO FESJUPLD;

GRANT DELETE, INSERT, SELECT, UPDATE ON FES.ZZ_POS_ITEM_NB TO FES_BATCH_ROLE;

GRANT DELETE, INSERT, SELECT, UPDATE ON FES.ZZ_POS_ITEM_NB TO FES_SA_ROLE;

GRANT DELETE, INSERT, SELECT, UPDATE ON FES.ZZ_POS_ITEM_NB TO FES_USER_ROLE;
