
DROP TABLE FES.ZZ_PSUB_REF_NB CASCADE CONSTRAINTS;

CREATE TABLE FES.ZZ_PSUB_REF_NB
(
  SUBSCRIBER         VARCHAR2(20 BYTE),
  SUB_NAME           VARCHAR2(100 BYTE),
  CELLULAR           VARCHAR2(20 BYTE),
  STAT               VARCHAR2(1 BYTE),
  SIM_NO             VARCHAR2(20 BYTE),
  DEALER             VARCHAR2(20 BYTE),
  ID_CARD_NO         VARCHAR2(20 BYTE),
  IMEI               VARCHAR2(20 BYTE),
  CONTACT_NO         VARCHAR2(20 BYTE),
  TELEX              VARCHAR2(15 BYTE),
  UNBILL_AMT         NUMBER(12,2),
  UNBILL_AMT_SIGN    VARCHAR2(1 BYTE),
  CUST_TYPE          VARCHAR2(40 BYTE),
  ACT_DATE           DATE,
  S_OFF_DATE         DATE,
  RPLAN              VARCHAR2(5 BYTE),
  IDD                VARCHAR2(1 BYTE),
  BAR_STATUS         VARCHAR2(1 BYTE),
  DISCON_REASON      VARCHAR2(40 BYTE),
  LAST_PAYMENT_DATE  DATE,
  OS_MINUTE          NUMBER(10),
  OBX_IND            VARCHAR2(1 BYTE),
  BAR_DATE           DATE,
  OBX_DATE           DATE,
  PAYMENT_METHOD     VARCHAR2(40 BYTE),
  BILL_DAY           NUMBER(5),
  DIVERT_CODE        VARCHAR2(15 BYTE),
  USER_REF           VARCHAR2(255 BYTE),
  USER_NAME          VARCHAR2(40 BYTE),
  ACCOUNT_NO         VARCHAR2(20 BYTE)
)
TABLESPACE FESENCDATA01
PCTUSED    0
PCTFREE    0
INITRANS   10
MAXTRANS   255
STORAGE    (
            INITIAL          900M
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOLOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX FES.ZZ_PSUB_REF_NB_ID1 ON FES.ZZ_PSUB_REF_NB
(SUBSCRIBER)
LOGGING
TABLESPACE FESEXTI02
PCTFREE    10
INITRANS   10
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX FES.ZZ_PSUB_REF_NB_ID2 ON FES.ZZ_PSUB_REF_NB
(CONTACT_NO)
LOGGING
TABLESPACE FESEXTI02
PCTFREE    10
INITRANS   10
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX FES.ZZ_PSUB_REF_NB_ID3 ON FES.ZZ_PSUB_REF_NB
(CELLULAR, IMEI)
LOGGING
TABLESPACE FESEXTI02
PCTFREE    10
INITRANS   10
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX FES.ZZ_PSUB_REF_NB_ID4 ON FES.ZZ_PSUB_REF_NB
(ID_CARD_NO, SUBSCRIBER)
LOGGING
TABLESPACE FESENCDATA01
PCTFREE    10
INITRANS   10
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX FES.ZZ_PSUB_REF_NB_ID5 ON FES.ZZ_PSUB_REF_NB
(USER_REF)
LOGGING
TABLESPACE FESEXTI02
PCTFREE    10
INITRANS   10
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX FES.ZZ_PSUB_REF_NB_ID6 ON FES.ZZ_PSUB_REF_NB
(ACT_DATE, DEALER, RPLAN)
LOGGING
TABLESPACE FESEXTI02
PCTFREE    10
INITRANS   10
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX FES.ZZ_PSUB_REF_NB_ID7 ON FES.ZZ_PSUB_REF_NB
(S_OFF_DATE)
LOGGING
TABLESPACE FESEXTI02
PCTFREE    10
INITRANS   10
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX FES.ZZ_PSUB_REF_NB_ID8 ON FES.ZZ_PSUB_REF_NB
(SUBSTR("ID_CARD_NO",1,8))
LOGGING
TABLESPACE FESEXTI02
PCTFREE    10
INITRANS   10
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


DROP PUBLIC SYNONYM ZZ_PSUB_REF_NB;

CREATE PUBLIC SYNONYM ZZ_PSUB_REF_NB FOR FES.ZZ_PSUB_REF_NB;

GRANT DELETE, INSERT, SELECT, UPDATE ON FES.ZZ_PSUB_REF_NB TO FESJUPLD;

GRANT DELETE, INSERT, SELECT, UPDATE ON FES.ZZ_PSUB_REF_NB TO FES_BATCH_ROLE;

GRANT DELETE, INSERT, SELECT, UPDATE ON FES.ZZ_PSUB_REF_NB TO FES_SA_ROLE;

GRANT DELETE, INSERT, SELECT, UPDATE ON FES.ZZ_PSUB_REF_NB TO FES_USER_ROLE;

