----  ===   $FES_PROG/pos/download_cmd_GNV_NB
----  ===   $FES_LOG/pos/download_cmd_GNV_NB
----   bRptCustproDiffComparsion.java
INSERT INTO BACKEND_REPORT_CFG (PROGRAM_NAME,OUTPUTDIR,LOGDIR,SPOOLDIR,BACKUPDIR,FTPURL,FTPPORT,FTPLOGIN,FTPPASSWORD,FTPDIR,MAILFROM,MAILTO,MAILCC,SPTMAILTO,SENDER_NAME,MAILBCC,EMAIL_MODULE_NAME,EMAIL_PROGRAM_NAME) VALUES
('CustproDiffComparsion','$FES_PROG/pos/download_cmd_GNV_NB','$FES_LOG/pos/download_cmd_GNV_NB',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'JCZhang@smartone.com','JCZhang@smartone.com',NULL,'JCZhang@smartone.com',NULL,NULL,NULL,NULL);

----  bRptOsinvDiffComparison.java
INSERT INTO BACKEND_REPORT_CFG (PROGRAM_NAME,OUTPUTDIR,LOGDIR,SPOOLDIR,BACKUPDIR,FTPURL,FTPPORT,FTPLOGIN,FTPPASSWORD,FTPDIR,MAILFROM,MAILTO,MAILCC,SPTMAILTO,SENDER_NAME,MAILBCC,EMAIL_MODULE_NAME,EMAIL_PROGRAM_NAME) VALUES
('OsinvDiffComparison','$FES_PROG/pos/download_cmd_GNV_NB','$FES_LOG/pos/download_cmd_GNV_NB',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'JCZhang@smartone.com','JCZhang@smartone.com',NULL,'JCZhang@smartone.com',NULL,NULL,NULL,NULL);
